# Generated by Django 5.2.5 on 2025-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_oficio_tecnico_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
