# Generated by Django 5.2.5 on 2025-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_solicitud_estado_solicitud_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
