# Generated by Django 5.2.5 on 2025-08-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_solicitud_descripcion_solicitud_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cedula',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/'),
        ),
    ]
